# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/tmp/covo

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
      - run: cd covobeta
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #build and see what happens... !!!
      - run: yarn build
      - run:
           name: Deploy Master to Firebase
           command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
      # run tests!
      - run: yarn test


#  deploy-job:
#     docker:
#       - image: my-image
#     working_directory: /covo
#     steps:
#       - run:
#           name: Deploy Master to Firebase
#           command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN



  workflows:
    version: 2

    build_and_deploy:
      jobs:
        - build-and-deploy
#        - deploy-job:
#            requires:
#              - build-job
#              branches:
#              only: master
