# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/tmp/CoVoBETA
    steps:
      - checkout
      - run:
           name: Switch timezone to Paris
           command: sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

      # Download and cache dependencies
      - restore_cache:
          keys:
            - CoVoBETA-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
#            - master-cache-{{ arch }}-{{ .Branch }}
#            - master-cache

      - run: yarn install

      #save installs to cache for future use
      - save_cache:
          key: CoVoBETA-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      #build and see what happens... !!! !!!
      - run: CI="" && yarn build
      - run:
           name: Deploy Master to Firebase
           command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  firebase_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
